spring:
  datasource:
    username: your_mysql_username
    password: your_mysql_password
  data:
    redis:
      host: your_redis_host
      password: your_redis_password
  mail:
    username: your_email@qq.com
    password: your_email_auth_code
minio:
  url: http://your-minio-url:9000
  access-key: your_minio_access_key
  secret-key: your_minio_secret_key
  bucket-name: your_bucket_name
